---
- hosts: localhost
  connection: local
  gather_facts: no
  
  tasks:
   - name: Build RHEL6 Container with Ansible
     docker:
       image: rhel6/rhel
       docker_api_version: 1.22
       pull: missing
       detach: yes
       tty: yes
       state: started
